apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
  annotations:
    argocd-image-updater.argoproj.io/image-list: alexwhen/docker-2048
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds  
spec:
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      app: "2048"
  replicas: 4
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - image: alexwhen/docker-2048
          imagePullPolicy: Always
          name: "2048"
          ports:
            - containerPort: 80
              protocol: TCP
